steps:
  - id: 'python test python-app'
    name: 'python'
    dir: './python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install flask
        python -m unittest discover

  - id : 'docker build python-app'
    name: 'gcr.io/cloud-builders/docker'
    dir: './python'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/python-repo/python-app:${SHORT_SHA}',
      '.'
    ]

  - id : 'docker push python-app'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/${PROJECT_ID}/python-repo/python-app:${SHORT_SHA}'
    ]

  - id: 'Setting Nginx Image Tag'
    name: ubuntu
    dir: ./k8s
    args: ['bash','-c','sed -i "s,PYTHON_APP_IMAGE,us-central1-docker.pkg.dev/${PROJECT_ID}/python-repo/python-app:${SHORT_SHA}," deploy-gke.yaml']

  - id : 'deploy python-app to gke'
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=./k8s/deploy-gke.yaml
    - --location=${_LOCATION}
    - --cluster=${_CLUSTER}

substitutions:
  _CLUSTER: "gke-cluster"
  _LOCATION: "us-central1-a"