steps:
  # - id: 'python test python-app'
  #   name: 'python'
  #   dir: '/python'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       pip install flask
  #       python -m unittest discover 

  - name: 'python'
    entrypoint: 'python'
    dir: '/python'
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']

  - id : 'docker build python-app'
    name: 'gcr.io/cloud-builders/docker'
    dir: '/python'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/python-repo/python-app:${SHORT_SHA}',
      '.'
    ]

  - id : 'docker push hello python-app'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/${PROJECT_ID}/python-repo/python-app:${SHORT_SHA}'
    ]

  # - id: 'deploy python-app to gke'
  #   name: 'gcr.io/cloud-builders/gke-deploy'
  #   dir: '/kubernetes'
  #   args: [
  #     'deploy',
  #     '--dir=./',
  #     '--cluster=${CLUSTER_NAME}',
  #     '--region=${CLUSTER_LOCATION}',
  #     '--zone=${CLUSTER_LOCATION}'
  #   ]

