---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: "us-central1-docker.pkg.dev/${PROJECT_ID}/python-repo/python-app:${SHORT_SHA}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
          - containerPort: 5000
        envFrom:
          - secretRef:
              name: python-app-secret
          - configMapRef:
              name: python-app-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app-cm
data:
  LINK: www.linkedin.com/in/danielsidauruk
---
apiVersion: v1
kind: Secret
metadata:
  name: python-app-secret
stringData:
  PASSWORD: strong-password!
type: Opaque
