apiVersion: v1
kind: Service
metadata:
  name: python-app-service
anotations:
  cloud.google.com/load-balancer-type: External
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 80
      targetPort: 5000